apiVersion: v1
kind: Secret
metadata:
  name: jwt-symmetric-key
type: Opaque
stringData:
  jwks: |
    {
      "keys": [
        {
          "kty": "oct",           # 'oct' means Symmetric Key
          "alg": "HS256",     
          "k": "INSERT THE Base64URL OF ACCESS TOKEN SECRET HERE",  #--- paste the base64 of accestoekn secret here
          "use": "sig",
        }
      ]
    }

# then remove the example from the file name
# ther is a script for auth
