apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: graphql-service-route
  labels:
    app: togather
    service: graphql-srv
    jwt: enabled
    cors: enabled
    ratelimitGlobal: enabled
spec:
  parentRefs:
    - name: togather-gateway
      namespace: envoy-gateway

  rules:
    - name: graphql-private
      matches:
        - path:
            type: PathPrefix
            value: /graphql

      backendRefs:
        - name: graphql-srv
          port: 3009
