apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: feed-service-route
  labels:
    app: togather
    service: feed-srv
    jwt: enabled
    ratelimitGlobal: enabled # enables ratelimiter
spec:
  parentRefs:
    - name: togather-gateway
      namespace: envoy-gateway

  rules:
    - name: feed-private
      matches:
        - path:
            type: RegularExpression
            value: ^/api/v[0-9a-zA-Z]+/feed/.*

      backendRefs:
        - name: feed-srv
          port: 3007
