apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auth-service-admin-route
  labels:
    app: togather
    service: auth-srv
spec:
  parentRefs:
    - name: togather-gateway
      namespace: envoy-gateway

  rules:
    - name: admin-protected
      matches:
        - path:
            type: PathPrefix
            value: /api/v1/auth/admin/2fa/initiate
        - path:
            type: PathPrefix
            value: /api/v1/auth/admin/2fa/enable
      backendRefs:
        - name: auth-srv
          port: 3000
# these routes are only allowed for admins
