apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demoservice-route
spec:
  parentRefs:
    - name: togather-gateway
      namespace: envoy-gateway
  # hostnames:
  # - "www.togather.com"
  rules:
    - backendRefs:
        - kind: Service
          name: demo-service
          port: 4003 # service port

          # weight: 1 refer readme
      matches:
        - path:
            type: PathPrefix
            value: /
