apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: experience-service-route
  labels:
    app: togather
    service: experience-srv
    jwt: enabled
    cors: enabled
    ratelimitGlobal: enabled # enables ratelimiter
spec:
  parentRefs:
    - name: togather-gateway
      namespace: envoy-gateway

  rules:
    # All other auth routes are public
    - name: experience-private
      matches:
        - path:
            type: RegularExpression
            value: ^/api/v[0-9a-zA-Z]+/experience/.*

      backendRefs:
        - name: experience-srv
          port: 3001
