apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: local-ratelimit
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: demoservice-route # targetting demoservice route
  rateLimit:
    type: Local
    local:
      rules:
        - limit:
            requests: 50
            unit: Minute
# https://gateway.envoyproxy.io/docs/concepts/gateway_api_extensions/backend-traffic-policy/#precedence
