apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: cors
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: togather-gateway
  cors:
    allowOrigins:
      - "http://localhost:5173"
      - "http://localhost:5174" # added a backup
    allowMethods:
      - GET
      - POST
      - PATCH
      - DELETE
      - PUT
    # allowHeaders:
    #   - "x-header-1"
    # exposeHeaders:
    #   - "x-header-2"
    allowCredentials: true
# https://gateway.envoyproxy.io/docs/api/extension_types/#cors
