apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: websocket-service-route
  labels:
    app: togather
    service: websocket-srv
    jwt: enabled
spec:
  parentRefs:
    - name: togather-gateway
      namespace: envoy-gateway
      sectionName: http
  
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /ws
      
      backendRefs:
        - name: websocket-srv
          port: 3000