apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  KAFKA_KRAFT_MODE: "true"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-0:9093"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-0.kafka.svc.cluster.local:9092,EXTERNAL://localhost:30092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
  CLUSTER_ID: "6p4FOKXjRPOkKxQYEj1QZQ"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_DELETE_TOPIC_ENABLE: "true"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
