apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: partner-service-route
  labels:
    app: togather
    service: partner-srv
    jwt: enabled
    ratelimitGlobal: enabled # enables ratelimiter
spec:
  parentRefs:
    - name: togather-gateway
      namespace: envoy-gateway

  rules:
    # Partner service routes (for mutations - direct calls)
    - name: partner-private
      matches:
        - path:
            type: RegularExpression
            value: ^/api/v[0-9a-zA-Z]+/partner/.*

      backendRefs:
        - name: partner-srv
          port: 3002
